name: Model2FR
description: The codgen from model to fish-redux-template
version: 0.0.2
homepage: https://github.com/huang12zheng/Model2FR/model2code.git
author: huang12zheng <805104533@qq.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  ansicolor: ^1.0.2
  args: '>=0.12.1 <2.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
